### ISSUE TITLE
Update to OWHL.boards.entry.txt

### ISSUE THREAD

**Issue by rfrancolini** [millerlp/OWHL#1]
While trying to reset multiple OWHLs, the text provided in "OHWL.boards.entry.txt to copy into "boards.txt" was not working, and I was receiving an error stating `"upload.tool. is undefined"` However, replacing
`OWHLatmega328.upload.tool=arduino:avrdude`
 with
```
OWHLatmega328.upload.tool=avrdude
OWHLatmega328.upload.tool.default=avrdude
```
fixed the issue.

**Comment by millerlp** [comment]
Thank you for the suggestion. The change has been made in the repository.
